### Installation

In [40]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

###Cleaning

In [41]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [42]:
df.shape

(569, 33)

In [43]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [44]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

### train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

###Scaling

In [45]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)


In [46]:
X_train

array([[-2.80734300e-03, -4.88640424e-01, -7.66936783e-02, ...,
        -5.43031825e-01, -6.12830242e-01, -1.02164648e+00],
       [ 1.24358680e+00,  6.05152793e-01,  1.17542357e+00, ...,
         3.47955977e-01,  3.21224849e-01, -4.56980663e-01],
       [ 8.71655977e-01, -6.69012244e-01,  1.00271774e+00, ...,
         2.12265698e+00,  1.84663564e+00,  1.22404246e+00],
       ...,
       [-4.91144002e-01, -1.62405791e+00, -5.21205582e-01, ...,
        -1.20346848e-01,  3.22818800e-01, -4.67134494e-01],
       [ 1.50507655e-01,  9.24272167e-01,  9.68345578e-02, ...,
         3.17645115e-01, -6.86151973e-01, -8.93595394e-01],
       [-8.09130664e-01,  3.35697928e+00, -8.56337127e-01, ...,
        -1.28701195e+00,  5.62261719e-03, -6.27903484e-01]])

In [47]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,

###Label Encoding

In [50]:
label_encoding=LabelEncoder()
y_train=label_encoding.fit_transform(y_train)
y_test=label_encoding.transform(y_test)

In [51]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,

###Numpy array to tensar array

In [52]:
X_train_tensor=torch.from_numpy(X_train)
Y_train_tensor=torch.from_numpy(y_train)
X_test_tensor=torch.from_numpy(X_test)
Y_test_tensor=torch.from_numpy(y_test)

In [53]:
X_train_tensor.shape

torch.Size([455, 30])

In [54]:
Y_train_tensor.shape

torch.Size([455])

###Model Building

In [58]:
class MySimpleNN():
  def __init__(self, X):
    self.weights =torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias= torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    return torch.sigmoid(torch.matmul(X,self.weights)+self.bias)


  def loss_function(self, y_pred, y_train_tensor):
      # Clamp predictions to avoid log(0)
      epsilon = 1e-7
      y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

      # Calculate loss
      loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
      return loss


###Improtant Parameters

In [59]:
learning_rate = 0.1
epochs = 25

###Training Pipline

In [60]:
#create model

model= MySimpleNN(X_train_tensor)

#define loop

for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)

  #loss calculations
  loss=model.loss_function(y_pred,Y_train_tensor)

  #backward pass
  loss.backward()


  #paramters update
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epocs
  print(f'Epch: {epoch+1}, Loss: {loss.item()}')



Epch: 1, Loss: 3.2734501258847692
Epch: 2, Loss: 3.136496731662354
Epch: 3, Loss: 2.999105284044121
Epch: 4, Loss: 2.8619985679412903
Epch: 5, Loss: 2.7165825027653723
Epch: 6, Loss: 2.561207514612421
Epch: 7, Loss: 2.4065872271070545
Epch: 8, Loss: 2.2490476894231337
Epch: 9, Loss: 2.086780814928809
Epch: 10, Loss: 1.928977183055801
Epch: 11, Loss: 1.7762697332479975
Epch: 12, Loss: 1.6288635947361223
Epch: 13, Loss: 1.4870934068676895
Epch: 14, Loss: 1.3553334326596014
Epch: 15, Loss: 1.238559984227216
Epch: 16, Loss: 1.1378706689361902
Epch: 17, Loss: 1.0537053003372794
Epch: 18, Loss: 0.9856031145459513
Epch: 19, Loss: 0.9321295203691382
Epch: 20, Loss: 0.8910705244055183
Epch: 21, Loss: 0.8598501307073088
Epch: 22, Loss: 0.8359875096343176
Epch: 23, Loss: 0.8174055539653988
Epch: 24, Loss: 0.8025323660641173
Epch: 25, Loss: 0.7902587932721858


###Evaluation

In [65]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6206524968147278
